version: '3.4'

services:
    backend-service:
        build: ./backend
        volumes:
            - ./backend:/usr/src/app
        command: app.py
        networks:
            - web

    nginx-service:
        build: ./nginx
        depends_on: 
            - backend-service
        ports:
            - 8002:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./frontend/dist:/var/www
        networks:
            - web

networks:
    web: